# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/file_options_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0google/protobuf/internal/file_options_test.proto\x12\x1fgoogle.protobuf.python.internal\x1a google/protobuf/descriptor.proto\"\x1e\n\nFooOptions\x12\x10\n\x08\x66oo_name\x18\x01 \x01(\t:a\n\x0b\x66oo_options\x12\x1c.google.protobuf.FileOptions\x18\xac\xec\xb6\x39 \x01(\x0b\x32+.google.protobuf.python.internal.FooOptions')


FOO_OPTIONS_FIELD_NUMBER = 120436268
foo_options = DESCRIPTOR.extensions_by_name['foo_options']

_FOOOPTIONS = DESCRIPTOR.message_types_by_name['FooOptions']
FooOptions = _reflection.GeneratedProtocolMessageType('FooOptions', (_message.Message,), {
  'DESCRIPTOR' : _FOOOPTIONS,
  '__module__' : 'google.protobuf.internal.file_options_test_pb2'
  # @@protoc_insertion_point(class_scope:google.protobuf.python.internal.FooOptions)
  })
_sym_db.RegisterMessage(FooOptions)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(foo_options)

  DESCRIPTOR._options = None
  _FOOOPTIONS._serialized_start=119
  _FOOOPTIONS._serialized_end=149
# @@protoc_insertion_point(module_scope)
