# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/test_bad_identifiers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3google/protobuf/internal/test_bad_identifiers.proto\x12\x11protobuf_unittest\"\x1e\n\x12TestBadIdentifiers*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\x10\n\x0e\x41notherMessage2\x10\n\x0e\x41notherService:;\n\x07message\x12%.protobuf_unittest.TestBadIdentifiers\x18\x64 \x01(\t:\x03\x66oo:>\n\ndescriptor\x12%.protobuf_unittest.TestBadIdentifiers\x18\x65 \x01(\t:\x03\x62\x61r:>\n\nreflection\x12%.protobuf_unittest.TestBadIdentifiers\x18\x66 \x01(\t:\x03\x62\x61z:;\n\x07service\x12%.protobuf_unittest.TestBadIdentifiers\x18g \x01(\t:\x03quxB\x03\x90\x01\x01')


MESSAGE_FIELD_NUMBER = 100
message = DESCRIPTOR.extensions_by_name['message']
DESCRIPTOR_FIELD_NUMBER = 101
descriptor = DESCRIPTOR.extensions_by_name['descriptor']
REFLECTION_FIELD_NUMBER = 102
reflection = DESCRIPTOR.extensions_by_name['reflection']
SERVICE_FIELD_NUMBER = 103
service = DESCRIPTOR.extensions_by_name['service']

_TESTBADIDENTIFIERS = DESCRIPTOR.message_types_by_name['TestBadIdentifiers']
_ANOTHERMESSAGE = DESCRIPTOR.message_types_by_name['AnotherMessage']
TestBadIdentifiers = _reflection.GeneratedProtocolMessageType('TestBadIdentifiers', (_message.Message,), {
  'DESCRIPTOR' : _TESTBADIDENTIFIERS,
  '__module__' : 'google.protobuf.internal.test_bad_identifiers_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.TestBadIdentifiers)
  })
_sym_db.RegisterMessage(TestBadIdentifiers)

AnotherMessage = _reflection.GeneratedProtocolMessageType('AnotherMessage', (_message.Message,), {
  'DESCRIPTOR' : _ANOTHERMESSAGE,
  '__module__' : 'google.protobuf.internal.test_bad_identifiers_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.AnotherMessage)
  })
_sym_db.RegisterMessage(AnotherMessage)

_ANOTHERSERVICE = DESCRIPTOR.services_by_name['AnotherService']
if _descriptor._USE_C_DESCRIPTORS == False:
  TestBadIdentifiers.RegisterExtension(message)
  TestBadIdentifiers.RegisterExtension(descriptor)
  TestBadIdentifiers.RegisterExtension(reflection)
  TestBadIdentifiers.RegisterExtension(service)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _TESTBADIDENTIFIERS._serialized_start=74
  _TESTBADIDENTIFIERS._serialized_end=104
  _ANOTHERMESSAGE._serialized_start=106
  _ANOTHERMESSAGE._serialized_end=122
  _ANOTHERSERVICE._serialized_start=124
  _ANOTHERSERVICE._serialized_end=140
AnotherService = service_reflection.GeneratedServiceType('AnotherService', (_service.Service,), dict(
  DESCRIPTOR = _ANOTHERSERVICE,
  __module__ = 'google.protobuf.internal.test_bad_identifiers_pb2'
  ))

AnotherService_Stub = service_reflection.GeneratedServiceStubType('AnotherService_Stub', (AnotherService,), dict(
  DESCRIPTOR = _ANOTHERSERVICE,
  __module__ = 'google.protobuf.internal.test_bad_identifiers_pb2'
  ))


# @@protoc_insertion_point(module_scope)
