# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/unittest_mset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import unittest_mset_wire_format_pb2 as google_dot_protobuf_dot_unittest__mset__wire__format__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#google/protobuf/unittest_mset.proto\x12\x11protobuf_unittest\x1a/google/protobuf/unittest_mset_wire_format.proto\"Z\n\x17TestMessageSetContainer\x12?\n\x0bmessage_set\x18\x01 \x01(\x0b\x32*.proto2_wireformat_unittest.TestMessageSet\"\xf9\x01\n\x18TestMessageSetExtension1\x12\t\n\x01i\x18\x0f \x01(\x05\x12=\n\trecursive\x18\x10 \x01(\x0b\x32*.proto2_wireformat_unittest.TestMessageSet\x12\x19\n\rtest_aliasing\x18\x11 \x01(\tB\x02\x08\x02\x32x\n\x15message_set_extension\x12*.proto2_wireformat_unittest.TestMessageSet\x18\xb0\xa6^ \x01(\x0b\x32+.protobuf_unittest.TestMessageSetExtension1\"\xa1\x01\n\x18TestMessageSetExtension2\x12\x0b\n\x03str\x18\x19 \x01(\t2x\n\x15message_set_extension\x12*.proto2_wireformat_unittest.TestMessageSet\x18\xf9\xbb^ \x01(\x0b\x32+.protobuf_unittest.TestMessageSetExtension2\"n\n\rRawMessageSet\x12\x33\n\x04item\x18\x01 \x03(\n2%.protobuf_unittest.RawMessageSet.Item\x1a(\n\x04Item\x12\x0f\n\x07type_id\x18\x02 \x02(\x05\x12\x0f\n\x07message\x18\x03 \x02(\x0c\x42\x05H\x01\xf8\x01\x01')



_TESTMESSAGESETCONTAINER = DESCRIPTOR.message_types_by_name['TestMessageSetContainer']
_TESTMESSAGESETEXTENSION1 = DESCRIPTOR.message_types_by_name['TestMessageSetExtension1']
_TESTMESSAGESETEXTENSION2 = DESCRIPTOR.message_types_by_name['TestMessageSetExtension2']
_RAWMESSAGESET = DESCRIPTOR.message_types_by_name['RawMessageSet']
_RAWMESSAGESET_ITEM = _RAWMESSAGESET.nested_types_by_name['Item']
TestMessageSetContainer = _reflection.GeneratedProtocolMessageType('TestMessageSetContainer', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGESETCONTAINER,
  '__module__' : 'google.protobuf.unittest_mset_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.TestMessageSetContainer)
  })
_sym_db.RegisterMessage(TestMessageSetContainer)

TestMessageSetExtension1 = _reflection.GeneratedProtocolMessageType('TestMessageSetExtension1', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGESETEXTENSION1,
  '__module__' : 'google.protobuf.unittest_mset_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.TestMessageSetExtension1)
  })
_sym_db.RegisterMessage(TestMessageSetExtension1)

TestMessageSetExtension2 = _reflection.GeneratedProtocolMessageType('TestMessageSetExtension2', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGESETEXTENSION2,
  '__module__' : 'google.protobuf.unittest_mset_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.TestMessageSetExtension2)
  })
_sym_db.RegisterMessage(TestMessageSetExtension2)

RawMessageSet = _reflection.GeneratedProtocolMessageType('RawMessageSet', (_message.Message,), {

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
    'DESCRIPTOR' : _RAWMESSAGESET_ITEM,
    '__module__' : 'google.protobuf.unittest_mset_pb2'
    # @@protoc_insertion_point(class_scope:protobuf_unittest.RawMessageSet.Item)
    })
  ,
  'DESCRIPTOR' : _RAWMESSAGESET,
  '__module__' : 'google.protobuf.unittest_mset_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest.RawMessageSet)
  })
_sym_db.RegisterMessage(RawMessageSet)
_sym_db.RegisterMessage(RawMessageSet.Item)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_unittest__mset__wire__format__pb2.TestMessageSet.RegisterExtension(_TESTMESSAGESETEXTENSION1.extensions_by_name['message_set_extension'])
  google_dot_protobuf_dot_unittest__mset__wire__format__pb2.TestMessageSet.RegisterExtension(_TESTMESSAGESETEXTENSION2.extensions_by_name['message_set_extension'])

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\370\001\001'
  _TESTMESSAGESETEXTENSION1.fields_by_name['test_aliasing']._options = None
  _TESTMESSAGESETEXTENSION1.fields_by_name['test_aliasing']._serialized_options = b'\010\002'
  _TESTMESSAGESETCONTAINER._serialized_start=107
  _TESTMESSAGESETCONTAINER._serialized_end=197
  _TESTMESSAGESETEXTENSION1._serialized_start=200
  _TESTMESSAGESETEXTENSION1._serialized_end=449
  _TESTMESSAGESETEXTENSION2._serialized_start=452
  _TESTMESSAGESETEXTENSION2._serialized_end=613
  _RAWMESSAGESET._serialized_start=615
  _RAWMESSAGESET._serialized_end=725
  _RAWMESSAGESET_ITEM._serialized_start=685
  _RAWMESSAGESET_ITEM._serialized_end=725
# @@protoc_insertion_point(module_scope)
