# CMake generated Testfile for 
# Source directory: C:/Libraries/3rdPartyLibs/libpng-1.6.34_64
# Build directory: C:/Libraries/3rdPartyLibs/libpng-1.6.34_64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngtest.cmake")
else()
  add_test(pngtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-16-to-8.cmake")
else()
  add_test(pngvalid-gamma-16-to-8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-background.cmake")
else()
  add_test(pngvalid-gamma-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-expand16-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-background.cmake")
else()
  add_test(pngvalid-gamma-expand16-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-expand16-transform.cmake")
else()
  add_test(pngvalid-gamma-expand16-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-sbit.cmake")
else()
  add_test(pngvalid-gamma-sbit NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-threshold.cmake")
else()
  add_test(pngvalid-gamma-threshold NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-gamma-transform.cmake")
else()
  add_test(pngvalid-gamma-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-interlace-standard.cmake")
else()
  add_test(pngvalid-progressive-interlace-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-size.cmake")
else()
  add_test(pngvalid-progressive-size NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-progressive-standard.cmake")
else()
  add_test(pngvalid-progressive-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-standard.cmake")
else()
  add_test(pngvalid-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngvalid-transform.cmake")
else()
  add_test(pngvalid-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-none.cmake")
else()
  add_test(pngstest-1.8-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-1.8-alpha.cmake")
else()
  add_test(pngstest-1.8-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-none.cmake")
else()
  add_test(pngstest-linear-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-linear-alpha.cmake")
else()
  add_test(pngstest-linear-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-none.cmake")
else()
  add_test(pngstest-none-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-none-alpha.cmake")
else()
  add_test(pngstest-none-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-none.cmake")
else()
  add_test(pngstest-sRGB-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngstest-sRGB-alpha.cmake")
else()
  add_test(pngstest-sRGB-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-discard.cmake")
else()
  add_test(pngunknown-discard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-IDAT.cmake")
else()
  add_test(pngunknown-IDAT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-if-safe.cmake")
else()
  add_test(pngunknown-if-safe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sAPI.cmake")
else()
  add_test(pngunknown-sAPI NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-save.cmake")
else()
  add_test(pngunknown-save NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-sTER.cmake")
else()
  add_test(pngunknown-sTER NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngunknown-vpAg.cmake")
else()
  add_test(pngunknown-vpAg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-quick.cmake")
else()
  add_test(pngimage-quick NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Release/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/Debug/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/MinSizeRel/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/RelWithDebInfo/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34_64/tests/pngimage-full.cmake")
else()
  add_test(pngimage-full NOT_AVAILABLE)
endif()
