.TH ControlPanel 1 "April 2021"
.SH NAME
ControlPanel \- Configure desktop settings for FOX Toolkit applications
.SH SYNOPSIS
\fBControlPanel\fP
.SH DESCRIPTION
.LP
The ControlPanel allows the user to change the color themes, fonts, and file bindings of
FOX Toolkit based programs.

.SH USAGE
.LP
The ControlPanel has three tabs: \fBThemes\fP, \fBBindings\fP, and \fBGeneral\fP.

.br
The Themes tab is used to control color themes, individual colors, and the system
font.

.br
The Bindings tab is used to associate file extension-associations with a description,
command, and mime-type.  The user can also assign icons.

.br
The General tab is used to control some common parameters of FOX Toolkit programs, such as
tooltip delay, mouse wheel speed, and so on.

.SH AUTHOR
This man page was written by Jeroen van der Zijp <jeroen@fox-toolkit.net>.
