# CMake generated Testfile for 
# Source directory: C:/Libraries/3rdPartyLibs/libpng-1.6.34
# Build directory: C:/Libraries/3rdPartyLibs/libpng-1.6.34
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;641;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;641;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;641;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngtest "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngtest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;641;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;646;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;646;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;646;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-16-to-8 "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;646;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-16-to-8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;648;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;648;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;648;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;648;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;650;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;650;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;650;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;650;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;652;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;652;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;652;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;652;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;654;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;654;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;654;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-background "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;654;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;656;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;656;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;656;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;656;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;658;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;658;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;658;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-sbit "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;658;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-sbit NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;660;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;660;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;660;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-threshold "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;660;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-threshold NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;662;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;662;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;662;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;662;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;664;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;664;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;664;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-interlace-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;664;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-interlace-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;666;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;666;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;666;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-size "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;666;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-size NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;668;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;668;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;668;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;668;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;670;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;670;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;670;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-standard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;670;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;672;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;672;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;672;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-transform "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngvalid.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;672;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngvalid-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-1.8-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-1.8-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-linear-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-linear-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-none-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-none-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-none "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-sRGB-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-alpha "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngstest.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;723;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngstest-sRGB-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;733;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;733;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;733;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-discard "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;733;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-discard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;734;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;734;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;734;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-IDAT "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;734;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-IDAT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;735;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;735;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;735;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-if-safe "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;735;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-if-safe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;736;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;736;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;736;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sAPI "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;736;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-sAPI NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;737;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;737;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;737;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-save "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;737;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-save NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;738;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;738;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;738;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sTER "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;738;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-sTER NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;739;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;739;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;739;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-vpAg "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngunknown.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;739;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngunknown-vpAg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;744;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;744;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;744;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-quick "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;744;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngimage-quick NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Release/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;745;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/libpng16d.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/Debug/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;745;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/MinSizeRel/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;745;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-full "C:/CMake/bin/cmake.exe" "-DLIBPNG=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=C:/Libraries/3rdPartyLibs/libpng-1.6.34/RelWithDebInfo/pngimage.exe" "-P" "C:/Libraries/3rdPartyLibs/libpng-1.6.34/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;614;add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;745;png_add_test;C:/Libraries/3rdPartyLibs/libpng-1.6.34/CMakeLists.txt;0;")
else()
  add_test(pngimage-full NOT_AVAILABLE)
endif()
