# CMake generated Testfile for 
# Source directory: C:/Librerias/SUMOLibraries/proj-7.2.0/test
# Build directory: C:/Librerias/SUMOLibraries/proj-7.2.0/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Builtins "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;4;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Builtins "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/builtins.gie")
  set_tests_properties(Builtins PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;4;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Builtins NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Builtins2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;5;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Builtins2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/more_builtins.gie")
  set_tests_properties(Builtins2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;5;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Builtins2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Axisswap "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;6;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Axisswap "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/axisswap.gie")
  set_tests_properties(Axisswap PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;6;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Axisswap NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Deformation "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;7;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Deformation "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/deformation.gie")
  set_tests_properties(Deformation PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;7;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Deformation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Ellipsoid "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;8;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Ellipsoid "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/ellipsoid.gie")
  set_tests_properties(Ellipsoid PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;8;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Ellipsoid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GDA "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;9;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GDA "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/GDA.gie")
  set_tests_properties(GDA PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;9;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GDA NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(4D-API-cs2cs-style "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;10;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(4D-API-cs2cs-style "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/4D-API_cs2cs-style.gie")
  set_tests_properties(4D-API-cs2cs-style PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;10;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(4D-API-cs2cs-style NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DHDN_ETRS89 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;11;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DHDN_ETRS89 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/DHDN_ETRS89.gie")
  set_tests_properties(DHDN_ETRS89 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;11;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(DHDN_ETRS89 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Unitconvert "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;12;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Unitconvert "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/unitconvert.gie")
  set_tests_properties(Unitconvert PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;12;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(Unitconvert NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(geotiff_grids "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;13;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(geotiff_grids "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/geotiff_grids.gie")
  set_tests_properties(geotiff_grids PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;13;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(geotiff_grids NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_hemi "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;14;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_hemi "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_hemi.gie")
  set_tests_properties(adams_hemi PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;14;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(adams_hemi NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_ws1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;15;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_ws1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_ws1.gie")
  set_tests_properties(adams_ws1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;15;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(adams_ws1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(adams_ws2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;16;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(adams_ws2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/adams_ws2.gie")
  set_tests_properties(adams_ws2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;16;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(adams_ws2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(guyou "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;17;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(guyou "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/guyou.gie")
  set_tests_properties(guyou PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;17;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(guyou NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(peirce_q "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;18;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(peirce_q "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/peirce_q.gie")
  set_tests_properties(peirce_q PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;18;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(peirce_q NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(defmodel "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;19;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(defmodel "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/defmodel.gie")
  set_tests_properties(defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;19;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(defmodel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(tinshift "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/tinshift.gie")
  set_tests_properties(tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;20;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(tinshift "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gie/tinshift.gie")
  set_tests_properties(tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;20;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(tinshift NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.1-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;24;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.1-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.1-jhs.gie")
  set_tests_properties(GIGS-5101.1-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;24;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.1-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.2-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;25;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.2-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.2-jhs.gie")
  set_tests_properties(GIGS-5101.2-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;25;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.2-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.3-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;26;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.3-jhs "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.3-jhs.gie")
  set_tests_properties(GIGS-5101.3-jhs PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;26;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.3-jhs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5101.4-jhs-etmerc "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;27;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5101.4-jhs-etmerc "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5101.4-jhs-etmerc.gie")
  set_tests_properties(GIGS-5101.4-jhs-etmerc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;27;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5101.4-jhs-etmerc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5102.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;30;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5102.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5102.1.gie")
  set_tests_properties(GIGS-5102.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;30;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5102.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;32;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.1.gie")
  set_tests_properties(GIGS-5103.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;32;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;33;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.2.gie")
  set_tests_properties(GIGS-5103.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;33;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5103.3 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;34;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5103.3 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5103.3.gie")
  set_tests_properties(GIGS-5103.3 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;34;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5103.3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5104 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5104.gie")
  set_tests_properties(GIGS-5104 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;35;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5104 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5104.gie")
  set_tests_properties(GIGS-5104 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;35;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5104 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5105.2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;37;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5105.2 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5105.2.gie")
  set_tests_properties(GIGS-5105.2 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;37;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5105.2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5106 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;38;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5106 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5106.gie")
  set_tests_properties(GIGS-5106 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;38;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5106 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5107 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;39;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5107 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5107.gie")
  set_tests_properties(GIGS-5107 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;39;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5107 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5109 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;41;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5109 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5109.gie")
  set_tests_properties(GIGS-5109 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;41;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5109 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5111.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;43;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5111.1 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5111.1.gie")
  set_tests_properties(GIGS-5111.1 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;43;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5111.1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5112 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;45;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5112 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5112.gie")
  set_tests_properties(GIGS-5112 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;45;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5112 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5113 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;46;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5113 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5113.gie")
  set_tests_properties(GIGS-5113 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;46;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5113 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5201 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;47;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5201 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5201.gie")
  set_tests_properties(GIGS-5201 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;47;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5201 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GIGS-5208 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie_d.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;54;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GIGS-5208 "C:/Librerias/SUMOLibraries/proj-7.2.0/bin/gie.exe" "C:/Librerias/SUMOLibraries/proj-7.2.0/test/gigs/5208.gie")
  set_tests_properties(GIGS-5208 PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_LIB=C:/Librerias/SUMOLibraries/proj-7.2.0/data/for_tests" WORKING_DIRECTORY "C:/Librerias/SUMOLibraries/proj-7.2.0/test" _BACKTRACE_TRIPLES "C:/Librerias/SUMOLibraries/proj-7.2.0/cmake/ProjTest.cmake;31;add_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;54;proj_add_gie_test;C:/Librerias/SUMOLibraries/proj-7.2.0/test/CMakeLists.txt;0;")
else()
  add_test(GIGS-5208 NOT_AVAILABLE)
endif()
subdirs("cli")
subdirs("unit")
