# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "C:/SUMOLibraries/gl2ps-1.4.0;C:/SUMOLibraries/gl2ps-1.4.0")
set(CPACK_CMAKE_GENERATOR "Visual Studio 16 2019")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "TODO.txt;C:/SUMOLibraries/gl2ps-1.4.0;/CVS/;/.svn;/.git;~$;DS_Store$;/tmp/;/bin/;/lib/")
set(CPACK_INSTALLED_DIRECTORIES "C:/SUMOLibraries/gl2ps-1.4.0;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:\SUMOLibraries\gl2ps-1.4.0")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "gl2ps")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "gl2ps")
set(CPACK_OUTPUT_CONFIG_FILE "C:/SUMOLibraries/gl2ps-1.4.0/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/SUMOLibraries/gl2ps-1.4.0/README.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "An OpenGL to PostScript (and PDF, and SVG...) printing library")
set(CPACK_PACKAGE_EXECUTABLE "gl2ps;gl2ps")
set(CPACK_PACKAGE_FILE_NAME "gl2ps-1.4.0-source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "gl2ps")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "gl2ps")
set(CPACK_PACKAGE_NAME "gl2ps")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Christophe Geuzaine")
set(CPACK_PACKAGE_VERSION "1.4.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "4")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/SUMOLibraries/gl2ps-1.4.0/COPYING.LGPL")
set(CPACK_RESOURCE_FILE_README "C:/SUMOLibraries/gl2ps-1.4.0/README.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/SUMOLibraries/gl2ps-1.4.0/README.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "TODO.txt;C:/SUMOLibraries/gl2ps-1.4.0;/CVS/;/.svn;/.git;~$;DS_Store$;/tmp/;/bin/;/lib/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/SUMOLibraries/gl2ps-1.4.0;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/SUMOLibraries/gl2ps-1.4.0/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "gl2ps-1.4.0-source")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/SUMOLibraries/gl2ps-1.4.0/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
